import { IconConfig } from '../Icon/index'
import { PackagesCategoryEnum } from '@/packages/index.d'
import { ChatCategoryEnum, ChatCategoryEnumName } from '../index.d'

const iconNames = [
  'uim:adobe',
  'uim:airplay',
  'uim:align',
  'uim:align-alt',
  'uim:android-alt',
  'uim:angle-double-down',
  'uim:angle-double-left',
  'uim:angle-double-right',
  'uim:angle-double-up',
  'uim:angle-down',
  'uim:angle-left',
  'uim:angle-right',
  'uim:angle-up',
  'uim:apple',
  'uim:apple-alt',
  'uim:apps',
  'uim:bag',
  'uim:battery-bolt',
  'uim:bing',
  'uim:box',
  'uim:briefcase',
  'uim:calender',
  'uim:chart',
  'uim:chart-pie',
  'uim:circle-layer',
  'uim:clinic-medical',
  'uim:clock',
  'uim:comment-alt',
  'uim:comment-alt-dots',
  'uim:docker',
  'uim:download-alt',
  'uim:dribbble',
  'uim:dropbox',
  'uim:entry',
  'uim:exclamation-circle',
  'uim:exclamation-triangle',
  'uim:exit',
  'uim:facebook',
  'uim:facebook-messenger',
  'uim:facebook-messenger-alt',
  'uim:google-drive',
  'uim:google-play',
  'uim:graph-bar',
  'uim:head-side-mask',
  'uim:horizontal-align-left',
  'uim:hospital',
  'uim:house-user',
  'uim:image-v',
  'uim:key-skeleton',
  'uim:layer-group',
  'uim:layers-alt',
  'uim:link-h',
  'uim:microscope',
  'uim:microsoft',
  'uim:object-group',
  'uim:object-ungroup',
  'uim:paypal',
  'uim:refresh',
  'uim:repeat',
  'uim:right-indent-alt',
  'uim:rocket',
  'uim:shield-plus',
  'uim:social-distancing',
  'uim:telegram-alt',
  'uim:user-md',
  'uim:toilet-paper',
  'uim:youtube'
]
const iconList = iconNames.map(name => ({
  ...IconConfig,
  category: ChatCategoryEnum.UNICONS,
  categoryName: ChatCategoryEnumName.UNICONS,
  package: PackagesCategoryEnum.ICONS,
  image: name,
  icon: name,
  dataset: name,
  title: name.replace('uim:', ''),
  virtualComponent: './components/Icons/Icon' // 虚拟组件路径，尾部不跟 ‘/’，相对于 /packages/index.ts 文件的位置
}))

export default iconList
